### ISSUE TITLE
st.align 함수가 없음

### ISSUE THREAD

**Issue by sika7492** [bluenight12/AIW#1]
camera.py를 테스트 해보려고 했는데 

아래와 같은 에러가 나옵니다.

혹시 추가로 설치해야하는 라이브러리가 있을지 궁금합니다.

Traceback (most recent call last):
  File "/home/song/PycharmProjects/pythonProject/.venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "/home/song/PycharmProjects/pythonProject/UI/AIW/pages/camera.py", line 53, in <module>
    main()
  File "/home/song/PycharmProjects/pythonProject/UI/AIW/pages/camera.py", line 14, in main
    with st.align('middle'):
AttributeError: module 'streamlit' has no attribute 'align'

**Comment by bluenight12** [comment]
어제 정렬테스트한다고 이것저것하다가 남겨놓은거라 조금 있다가 고친 코드 올려드릴게요

**Comment by sika7492** [comment]
넵 알겠습니다

**Comment by bluenight12** [comment]
새로 올렸습니다
