### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sika7492** [bluenight12/AIW#34]
Traceback (most recent call last):
  File "/home/dagong/Desktop/AIW/.venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "/home/dagong/Desktop/AIW/AIW/pages/voice.py", line 8, in <module>
    from googletrans import Translaor
  File "/home/dagong/Desktop/AIW/.venv/lib/python3.10/site-packages/googletrans/__init__.py", line 7, in <module>
    from googletrans.client import Translator
  File "/home/dagong/Desktop/AIW/.venv/lib/python3.10/site-packages/googletrans/client.py", line 29, in <module>
    class Translator:
  File "/home/dagong/Desktop/AIW/.venv/lib/python3.10/site-packages/googletrans/client.py", line 32, in Translator
    proxies: typing.Dict[str, httpcore._sync.interfaces.RequestInterface] = None,
AttributeError: module 'httpcore._sync' has no attribute 'interfaces'

**Comment by sika7492** [comment]
pip install httpcore==1
